### ISSUE TITLE
Support of `v`-prefixed tags?

### ISSUE THREAD

**Issue by urigeva93** [autotag-dev/autotag#93]
Hey, 

Are `v`-prefixed tags supported?
With a little experiment I did (with the latest version of `autotag`), this didn't seem to work for me:
My latest tag was `v1.0.4`,  so I'd expect my next (patch) tag would be `v1.0.5`. From some reason, I've got `1.0.5` (without `v`):

```bash
❯ git describe --abbrev=0 --tags
v1.0.4
```

and when running `autotag`:
```bash
❯ ./bin/autotag -n
1.0.5
```

I even saw there is a flag that let you disable it (`-e, --empty-version-prefix   Do not prepend v to version tag`), so that hints it should work by default, no?

Is it on purpose? If yes, what am I doing wrong and how can I config it to work with `v`-prefixed tags?

Thanks!

**Comment by urigeva93** [comment]
Ok, I think I've found the issue:  regardless whether the tag is prefixed or not, The print line is without it (as can be seen [here](https://github.com/pantheon-systems/autotag/blob/master/autotag/main.go#L68)). Since I used the `-n` flag, it didn't apply the prefix logic ([here](https://github.com/pantheon-systems/autotag/blob/master/autotag.go#L447-L450)), and just logged the latest version (which is always without `v`). This is why I thought it didn't work. 

I think this is a bit misleading, and maybe it's best to log the exact tag which is going to be created.

**Comment by spheromak** [comment]
I see your point. I think the intent here is to communicate just the numeric version that will be iterated. Historically we had used this for storing some related info that did not want the `v` prefix. I see how coming into the tool fresh means this behavior may be a bit surprising.  I don't think we should change the default behavior as it's already being used as-is. Though I think it's a good candidate for a next  "major" bump or as a new flag, but I am also weary of adding more flags.

**Comment by urigeva93** [comment]
@spheromak thanks for the answer. I guess I can manually prefix the `v` before pushing the tag, just wanted to raise awareness of that behavior

**Comment by joemiller** [comment]
it makes sense to me that `-n` (print next version; don't create git tag) would output with the same `v` prefix as would be used if a tag was created. but as @spheromak mentioned this would be a breaking change. i'm not sure we would even want to fix it in a v2 release though
